//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShveinFabric.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class FurunitureProduct
    {
        public string FurunitureArticle { get; set; }
        public int ProductArticle { get; set; }
        public string Placement { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Turn { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Furuniture Furuniture { get; set; }
        public virtual Product Product { get; set; }
    }
}
