//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShveinFabric.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderedProducts
    {
        public int ArticleProduct { get; set; }
        public int NumberOrder { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Product Product { get; set; }
    }
}
