//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShveinFabric.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int Party { get; set; }
        public string FutunitureArticle { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Furuniture Furuniture { get; set; }
    }
}
